### ISSUE TITLE
The microcontroller module seems not to be in this circuitpython firmware build

### ISSUE THREAD

**Issue by garycmartin** [python-ugame/vacuum-invaders#1]
I've not managed to get this demo to run yet, but in the process of debugging and checking the library imports I spotted:

```
>>> import microcontroller
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'microcontroller'
```

All the other imports in game.py worked fine.

I also went through the  format.uf2 and firmware.uf2 troubleshooting steps to re-flash in case there was a new version of CircuitPython but still has the same error (it's still 2.2.0-rc1-9-g2523b559b, Adafruit are currently on 2.3.1).

**Comment by deshipu** [comment]
Ouch, looks like I used a feature that has only been introduced in CircuitPython 3.0, sorry about that. I will need to revert that.

**Comment by deshipu** [comment]
I now reverted that commit. Sorry for the trouble.

**Comment by deshipu** [comment]
By the way, you want to only copy the .mpy file and not the .py file, otherwise you will run out of memory.
